# sonar_token=sqp_930e75aa46a544697e72b4071bc1ec15de83a198

# must be unique in a given SonarQube instance
# sonar.projectKey=test-ci
sonar.organization=fernandopascoalbr
sonar.projectKey=test-ga

sonar.sources=src
sonar.exclusions=**/*.test.js

sonar.tests=src
sonar.test.inclusions=**/*.test.js
sonar.coverage.exclusions=**/*.test.js
# sonar.host.url=http://localhost:9000
# sonar.login=sqp_930e75aa46a544697e72b4071bc1ec15de83a198
sonar.javascript.lcov.reportPaths=lcov.coverage

# --- optional properties ---

# defaults to project key
#sonar.projectName=My project
# defaults to 'not provided'
#sonar.projectVersion=1.0
 
# Path is relative to the sonar-project.properties file. Defaults to .
 
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8