
name: ci-node-workflow
on:
  pull_request:
    branches:
      - develop
      - main
jobs: 
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['24.4.0', '18.20.8']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - run: npm test
      - run: npm start